#!/bin/sh

bspc config border_width 0
bspc config window_gap 0
bspc config top_padding 15
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true

bspc config focused_locked_border_color   "#CFB776"
bspc config active_locked_border_color    "#5C5955"
bspc config normal_locked_border_color    "#34322E"
bspc config focused_sticky_border_color   "#E3A5DA"
bspc config active_sticky_border_color    "#5C5955"
bspc config normal_sticky_border_color    "#34322E"
bspc config focused_private_border_color  "#42CAD9"
bspc config active_private_border_color   "#5C5955"
bspc config normal_private_border_color   "#34322E"
bspc config urgent_border_color           "#F9A299"

# border
bspc config border_width 4

bspc config focused_border_color "#859900"
bspc config active_border_color "#5C5955"
bspc config normal_border_color "#34322E"
bspc config presel_border_color "#F6F9FF"

bspc rule -a Fzf:st-256color state=floating sticky=on
#bspc rule -a "Ldoce5viewer:ldoce5viewer" state=floating sticky=on
#bspc rule -a "tabbed:VimbT" state=floating sticky=on
#bspc rule -a "st-256color:terminaldropdown" state=floating sticky=on 
