#!/bin/sh

#bspc monitor -d "α" "β" "γ" "δ" "ε"
bspc monitor -d "1" "2" "3" "4" "5"

bspc config border_width          1
bspc config window_gap            0
bspc config split_ratio           0.618
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config top_padding           18
bspc config focus_follows_pointer true

#bspc config normal_border_color   "#000000"
#bspc config focused_border_color  "#aaaaaa"
bspc config focused_border_color          "#6F7277"
bspc config active_border_color           "#5C5955"
bspc config normal_border_color           "#34322E"
bspc config presel_border_color           "#F6F9FF"
bspc config focused_locked_border_color   "#CFB776"
bspc config active_locked_border_color    "#5C5955"
bspc config normal_locked_border_color    "#34322E"
bspc config focused_sticky_border_color   "#E3A5DA"
bspc config active_sticky_border_color    "#5C5955"
bspc config normal_sticky_border_color    "#34322E"
bspc config focused_private_border_color  "#42CAD9"
bspc config active_private_border_color   "#5C5955"
bspc config normal_private_border_color   "#34322E"
bspc config urgent_border_color           "#F9A299"

#bspc rule -a MPlayer  floating=on
#bspc rule -a skype    desktop="^4"
#bspc rule -a spotify  desktop="^5"
#bspc rule -a Chromium desktop="^1"

~/bin/status &
