#!/bin/bash

msg_age="$(( ($2 - $1) / 86400 ))"

if [ $msg_age -ge 30 ]; then
    format="%[%d/%m/%y]" # '20/01/11'
elif [ $msg_age -ge 1 ]; then
    format="%8[%d %b]" # ' 20 Jan'
else
    format="%[ %_I:%M%P]" # ' 6:41pm'
fi

echo "%-18.18F %Z %s %* $format%"
