#!/bin/bash
echo "Installing personal dotfiles"

test -z "$1" && echo "Please, specify dotfiles directory" && exit 1

cd $1

install -d ~/.config

# bind keys
install -d ~/.config/sxhkd
install -m755 config/sxhkd/* ~/.config/sxhkd

# rss feed
install -d ~/.newsbeuter
install -Dm644 newsbeuter/config ~/.newsbeuter
install -Dm644 newsbeuter/urls ~/.newsbeuter

# pdf
install -d ~/.config/zathura
install -Dm644 config/zathura/zathurarc ~/.config/zathura/zathurarc

# editor
install -Dd ~/.vim ~/.vim/bundle
install -Dm644 vimrc ~/.vimrc
install -Dm644 vim/ycm_extra_conf_c.py ~/.vim/.ycm_extra_conf_c.py
install -Dm644 vim/ycm_extra_conf_cpp.py ~/.vim/.ycm_extra_conf_cpp.py

# terminal
install -Dm644 tmux.conf ~/.tmux.conf
#install -Dm644 screenrc ~/.screenrc

install -d ~/.tmuxinator
install -Dm644 tmuxinator/cs.yml ~/.tmuxinator

# applications
install -d ~/.local ~/.local/share ~/.local/share/applications
install -Dm644 local/share/applications/vim.desktop ~/.local/share/applications/vim.desktop
install -Dm644 local/share/applications/zathura-tabbed.desktop ~/.local/share/applications/zathura-tabbed.desktop

# shell
install -Dm644 zshrc ~/.zshrc
#install -Dm644 bash_profile ~/.bash_profile
#install -Dm644 bashrc ~/.bashrc
#install -Dm644 bashrc.d/* ~/.bashrc.d

# mpd, ncmpcpp
install -d ~/.ncmpcpp
install -Dm644 ncmpcpp/config ~/.ncmpcpp/config
install -Dm644 mpdconf ~/.mpdconf

# gdb
install -Dm644 gdbinit ~/.gdbinit

# git
install gitconfig ~/.gitconfig

# surf
install -d ~/.surf
install -Dm644 surf/script.js ~/.surf

# mail
install -d ~/.mutt
install -Dm644 mutt/* ~/.mutt
install -Dm644 mbsyncrc ~/.mbsyncrc
install -Dm600 msmtprc ~/.msmtprc

# desktop notification
install -d ~/.config/dunst
install -Dm644 config/dunst/dunstrc ~/.config/dunst/dunstrc

# systemd
install -d ~/.config/systemd  ~/.config/systemd/user
install -Dm644 config/systemd/user/fetchmail.service ~/.config/systemd/user
install -Dm644 config/systemd/user/mpd.service ~/.config/systemd/user
install -Dm644 config/systemd/user/mpd.socket ~/.config/systemd/user
install -Dm644 config/systemd/user/sxhkd.service ~/.config/systemd/user
install -Dm644 config/systemd/user/dropbox.service ~/.config/systemd/user

# x session
install -Dm644 xinitrc ~/.xinitrc
install -Dm644 Xresources ~/.Xresources
#install -Dm644 Xmodmap ~/.Xmodmap # xmodmap is old, using sxkbd instead

# irc, im
install -d ~/.irssi ~/.irssi/scripts
install -Dm644 irssi/config ~/.irssi
install -Dm644 irssi/startup ~/.irssi
install -Dm644 irssi/xchat.theme ~/.irssi
install -Dm644 irssi/xchatnickcolor.pl ~/.irssi
install -Dm644 irssi/scripts/* ~/.irssi/scripts

# file manager
install -d ~/.config/ranger
install -Dm644 config/ranger/* ~/.config/ranger

# panel
install -Dm644 config/tint2/* ~/.config/tint2

# composite
install -Dm644 config/compton.conf ~/.config/compton.conf

# conky
#install -Dm644 conkyrc ~/.conkyrc

# mplayer
install -d ~/.mplayer
install -Dm644 mplayer/config ~/.mplayer/config

# scripts
#install -d ~/bin
#install -Dm755 scripts/* ~/bin

# idesk
install -d ~/.idesktop ~/.idesktop/icons
install -Dm644 ideskrc ~/.ideskrc
install -Dm644 idesktop/launcher.lnk ~/.idesktop
install -Dm644 idesktop/arch-linux-1920x1200.png ~/.idesktop
install -Dm644 idesktop/icons/* ~/.idesktop/icons

# fonts
install -d ~/.fonts
install -Dm644 fonts/* ~/.fonts && mkfontscale ~/.fonts; mkfontdir ~/.fonts

# window mangers
# i3
#install -Dm644 i3/config ~/.i3/config
#install -Dm755 i3/winmenu.py ~/.i3/winmenu.py
#install -Dm644 i3/conkyrc ~/.i3/conkyrc
#install -Dm755 i3/conky ~/.i3/conky
# dwm
#install -Dm755 dwm/autostart.sh ~/.dwm/autostart.sh
# openbox
#install -Dm644 config/openbox/* ~/.config/openbox
# bspwm
install -d ~/.config/bspwm
install -Dm755 config/bspwm/* -t ~/.config/bspwm
