#!/bin/sh
brw="surf-tabbed"

xdotool search --maxdept 1 --onlyvisible --classname "surf-tabbed" windowunmap ||
    xdotool search --maxdept 1 --classname "surf-tabbed" windowmap ||
    $brw www.google.com &
