#!/usr/bin/bash


### MAIN ###

# The most robust getopt
args=$(getopt -q -o c:f: -l "classname:,first:" -n "$(basename $0)" -- "$@")
test $# -lt 2 -o $? -ne 0 && printf "usage: -c classname command\n" && exit 1
eval set -- "$args"; while true; do
    case "$1" in
        -c|--classname) shift; classname=$1; shift ;;
        -f|--first) shift; first=$1; shift ;;
        --) shift; break ;;
    esac
done # $@ will store all remaing args

# assume that all 'mapunmap' window are floating
bspc rule -a ${classname} -o floating=on


if xdotool search --onlyvisible --classname ${classname} windowunmap; then
    #echo "window is enabled, disable it" >> /tmp/.mapunmap.log
    true
else
    if xdotool search --classname ${classname} windowmap; then
        #echo "window is disabled, enable it" >> /tmp/.mapunmap.log
        true
    else
        #echo "create window first time with cmd: $@" >> /tmp/.mapunmap.log
        eval "$@"
        [ ! -z $first ] && eval "$first"
    fi
fi
