#!/usr/bin/bash


### MAIN ###

criteria=""

# The most robust getopt
args=$(getopt -q -o n:N:t:f: -l "instance:,class:,title:,first:" -n "$(basename $0)" -- "$@")
test $? -ne 0 && printf "usage: -c instance command\n" && exit 1
eval set -- "$args"; while true; do
    case "$1" in
        -n|--instance) shift; criteria="${criteria} -n $1"; shift ;;
        -N|--class) shift; criteria="${criteria} -N $1"; shift ;;
        -t|--title) shift; criteria="${criteria} -t $1"; shift ;;
        -f|--first) shift; first=$1; shift ;;
        --) shift; break ;;
    esac
done # $@ will store all remaing args

base="xdo id"
wactive=$($base)
wtarget=$(eval "${base} ${criteria}")

if [ "$?" -ne 0 ]; then # no target windows found
    #echo "window target is not found, launch window"
    eval "$@"
    [ ! -z $first ] && eval "$first"
else
    if echo $wtarget | grep -q $wactive; then
        #echo "window target is found at ${wtarget}, and shown, thus hide it"
        echo ${wtarget} | xargs xdo hide
    else
        #echo "window target is found at ${wtarget}, and hidden, thus re-show it"
        echo ${wtarget} | xargs xdo hide
        echo ${wtarget} | xargs xdo show
    fi
fi
