#!/usr/bin/bash

default="#90707070"

glyph_battery_charging="\uf100"
glyph_battery_20_0="\uf107"
glyph_battery_40_20="\uf106"
glyph_battery_60_40="\uf105"
glyph_battery_80_60="\uf104"
glyph_battery_80_90="\uf103"
glyph_battery_90_100="\uf102"
glyph_battery_100="\uf101"

bat_color="#99000000"

bat_info=$(acpi -b)

state=$(echo $bat_info | awk 'sub(/%/, "") {print $3}')
capacity=$(sed -n p "/sys/class/power_supply/BAT1/capacity")

if test "$state" = "Charging"; then
    bat_text="${glyph_battery_charging}"
elif test "$state" = "Full"; then
    bat_text="${glyph_battery_100}"
else
    if test $capacity -eq 100; then
        bat_text="${glyph_battery_100}"
    elif test $capacity -le 100 -a $capacity -gt 90; then
        bat_text="${glyph_battery_90_100}"
    elif test $capacity -le 90 -a $capacity -gt 80; then
        bat_text="${glyph_battery_80_90}"
    elif test $capacity -le 80 -a $capacity -gt 60; then
        bat_text="${glyph_battery_80_60}"
    elif test $capacity -le 60 -a $capacity -gt 40; then
        bat_text="${glyph_battery_60_40}"
    elif test $capacity -le 40 -a $capacity -gt 20; then
        bat_text="${glyph_battery_40_20}"
    elif test $capacity -le 20; then
        bat_text="%{Fred}${glyph_battery_20_0}"
    else
        bat_text="Unknown"
    fi
fi

#test -z ${capacity} && echo "" || echo "%{F${bat_color}}${bat_text} %{F${default}}${capacity}%%"
test -z ${capacity} && echo "" || echo "${bat_text}"
