#!/bin/bash
# mutt call with options -f phuoctaitp@gmail.com -- phuoctaitp@gmail.com
#echo $@ > /tmp/sendm.log

args=`getopt s:p:f: $*`
if [ $? != 0 ]
then
    echo 'Usage: cat <path-to-mail-file> | sendm -f <from-email> -- <to-email>'
    exit 2
fi

set -- $args
for i; do
    case "$i" in
    -f)
        from="$2"; shift;
        shift;;
    -s)
        smtp_server="$2"; shift;
        shift;;
    -p)
        pass_cmd=`$2`; shift;
        shift;;
    --)
        shift; break;;
    esac
done

user=$from
from_stmt='';

for to in $@; do
    from_stmt="${from_stmt}--mail-rcpt $to "
done

ssl_cert=/etc/ssl/cert.pem
#smtp_server="smtp.outlook.com:587"
pass_cmd=`gpg -dq ~/.gnupg/hotmail-tait.gpg| xargs -0 bash -c`

while read a;do echo $a; done | \
     curl -v --silent --sasl-ir --ssl-reqd --user "${user}"  \
    --cacert ${ssl_cert} \
    --oauth2-bearer ${pass_cmd} \
    --url ${smtp_server} \
    --mail-from "$from" \
    ${from_stmt} \
    --upload-file -
