#!/usr/bin/bash


session="tmux-urxvt-dropdown"
name="tmux-urxvt-dropdown"
title="URxvt Dropdown"

# The most robust getopt
args=$(getopt -o s:n:t: -l "session:,name:,title:" -n "$(basename $0)" -- "$@")
test $? -ne 0 && printf "usage: [-s|--session -n|--name -t|--title] \n" && exit 1
eval set -- "$args"; while true; do
    case "$1" in
        -s|--session) shift; session=$1; shift ;;
        -n|--name) shift; name=$1; shift ;;
        -t|--title) shift; title=$1; shift ;;
        --) shift; break ;;
    esac
done # $@ will store all remaing args

urxvtc -name "${name}" -title "${title}" -e $SHELL -c "tmux has-session && tmux attach || tmux new-session" &
