#!/usr/bin/zsh

perl_ext="kuake,default,matcher"
urxvt_name="urxvt-kuake"
shell=${SHELL}
session_name=${USER}

if test -z $(pgrep tmux | head -1); then
    tmux new-session -d -s ${session_name}

    # wait for session created
    #while ! $(tmux -q has-session); do ; done

    # ncmpcpp
    tmux new-window -dP -t $session_name:2
    tmux splitw -t $session_name:2 -v

    tmux splitw -t $session_name:2.0  -h

    tmux send-keys -t $session_name:2.0 archey enter
    tmux send-keys -t $session_name:2.1 ncmpcpp enter C-m
    tmux send-keys -t $session_name:2.2 htop enter


    # mutt
    tmux new-window -dP -t $session_name:3 mutt

    # irssi
    tmux new-window -dP -t $session_name:4 irssi
    tmux splitw -t $session_name:4 -h -p 17
    tmux send-keys -t $session_name:4 "cat ~/.irssi/nicklistfifo" C-m
    tmux select-pane -t $session_name:4.0

    # select first window
    tmux select-window -t $session_name:1
fi

# attach tmux to urxvt
urxvtc -name ${urxvt_name}  -pe ${perl_ext} -e ${shell} -c "tmux attach-session -t ${session_name}"
