#!/bin/sh
histfile=~/.config/vimb/history
histsize=1000


if xdotool search -classname 'VimbT'; then
    echo "<Esc>;tabopen $@<CR>" | socat - unix-connect:$(grep 'socket' /tmp/vimb.socket)
else
    tabbed -c -n 'VimbT' vimb --socket --dump --embed $@ > /tmp/vimb.socket
fi
