#!/usr/bin/bash

classname=$1

panel_pixel=18
border_pixel=1
padding=10

width=$(echo $(xrandr | grep "*" | awk '{print $1}' | cut -d'x' -f1) - $(($border_pixel*2))  - ${padding}*2 | bc)
height=$(echo $(xrandr | grep "*" | awk '{print $1}' | cut -d'x' -f2) - $(($border_pixel*2 + $panel_pixel)) - ${padding}*2 | bc)

xdotool search --classname ${classname} windowsize $width $height windowmove $padding $(($panel_pixel + $padding))
