#!/bin/sh

xidfile="/tmp/tabbed-zathura.xid"
xid="$([ -r $xidfile ] && cat $xidfile)"

if [ -n "$xid" ] && xprop -id "$xid" >/dev/null 2>&1 ; then
    zathura -e "$xid" "$@" >/dev/null 2>&1 &
else
    tabbed -c -f -dn 'zathura-tabbed' -r 2 zathura -e '' "$@" >"$xidfile" 2>/dev/null &
fi

